### ISSUE TITLE
One Primary account

### ISSUE THREAD

**Issue by Abhishekoodles1** [NEMPH/nem-apps-lib#5]
Can i create one primary wallet and then create its sub address in nem blockchain ? So that all balance can be consolidate in one account ?

**Comment by alvin-reyes** [comment]
If primary wallet meaning a nanowallet instance, then yes, you can create and manage multiple NEM address with it. 

https://nem.io/

There is also a way for you to manage sub-accounts from a master account. You can create sub accounts and convert those to multisig accounts via the master account. The catch is that multisig accounts cannot create transactions on their own, it needs to be initiated by a master account.

You can check out mulitisig feature here:

https://blog.nem.io/how-to-use-multi-signature-accounts/

Now if your intention is just to create a consolidation of accounts, I would suggest to just consolidate them on your application. Create a NEM account for each user, group them via your applications grouping mechanism and then use NEM REST API to query transaction details for each of the accounts.

https://docs.nem.io/en/nem-apis
